---
title: "Expt2_behavioral_analyses"
author: "Anna Ivanova"
date: "3/16/2021"
output: html_document
---


```{r setup, include=FALSE}
rm(list = ls())    # clear workspace

knitr::opts_chunk$set(echo = TRUE)
library(lme4)
library(lmerTest)
library(ggplot2)
library(dplyr)
library(tidyr)
library(patchwork)
library(emmeans)
```

# Read and clean the data

```{r read data, echo=FALSE}
dat = read.csv('../data/Expt2_data/study2.csv')

# Set up the contrasts and factor structure
# group - dummy coding with neurotypical as the reference level
# dimension - sum coding
dat$Group = factor(dat$Group, levels=c('Aphasia', 'Neurotypical', 'Parkinsons')) 
dat$Dimension = factor(dat$Dimension, levels=c('HD', 'LD'))
contrasts(dat$Dimension) = c(-0.5, 0.5)
colnames(attr(dat$Dimension, "contrasts")) = "LD>HD"
dat$Participant = factor(dat$Participant) 
```

# Summary 

```{r data means, echo=FALSE}
# Dimension only
dat.summ.acc.dim = dat %>% group_by(Group, Dimension, Participant) %>% 
  summarize(Accuracy = mean(Accuracy)) %>%
  group_by(Dimension) %>%
  summarize(meanAccuracy = mean(Accuracy),
            sdAccuracy = sd(Accuracy))

dat.summ.RT.dim = dat %>% group_by(Group, Dimension, Participant) %>% 
  summarize(Response.Time = mean(Response.Time)) %>%
  group_by(Dimension) %>%
  summarize(meanRT = mean(Response.Time),
            sdRT = sd(Response.Time))

# Group only
dat.summ.acc.group = dat %>% group_by(Group, Dimension, Participant) %>% 
  summarize(Accuracy = mean(Accuracy)) %>%
  group_by(Group) %>%
  summarize(meanAccuracy = mean(Accuracy),
            sdAccuracy = sd(Accuracy))

dat.summ.RT.group = dat %>% group_by(Group, Dimension, Participant) %>% 
  summarize(Response.Time = mean(Response.Time)) %>%
  group_by(Group) %>%
  summarize(meanRT = mean(Response.Time),
            sdRT = sd(Response.Time))

# by group and dimension 
dat.summ.acc = dat %>% group_by(Group, Dimension, Participant) %>% 
  summarize(Accuracy = mean(Accuracy)) %>%
  group_by(Group, Dimension) %>%
  summarize(meanAccuracy = mean(Accuracy),
            sdAccuracy = sd(Accuracy))

dat.summ.RT = dat %>% group_by(Group, Dimension, Participant) %>% 
  summarize(Response.Time = mean(Response.Time)) %>%
  group_by(Group, Dimension) %>%
  summarize(meanRT = mean(Response.Time),
            sdRT = sd(Response.Time))

# Case study - Aphasia 4
dat.summ.acc.A4= dat %>% 
  filter(Participant=='4_Aphasia') %>%
  group_by(Dimension) %>%
  summarize(meanAccuracy = mean(Accuracy),
            sdAccuracy = sd(Accuracy))

dat.summ.RT.A4 = dat %>% 
  filter(Participant=='4_Aphasia') %>%
  group_by(Dimension) %>%
  summarize(meanRT = mean(Response.Time),
            sdRT = sd(Response.Time))

write.csv(dat.summ.acc, 'Tables/E2_data_summary.csv')
```

# Accuracy
## Stats
### By group

We are aiming to estimate the effect of dimensionality on the Accuracy / False Alarm Rate / Response Time. We are treating category and participant as random effects. 

```{r stats acc, echo=FALSE}
m.acc = glmer(Accuracy ~ Dimension*Group + (1|Category) + (1|Participant), 
                      family = binomial(), 
                      data = dat)
summary(m.acc)
```

Follow-up comparisons:
```{r stats pairwise acc, echo=FALSE}
d = emmeans(m.acc, ~ Dimension) %>% 
    contrast("pairwise") 

emmeans(m.acc, ~ Group * Dimension) %>% 
    contrast("pairwise", by = "Group") %>% 
    rbind(d) %>%
    summary(by=NULL, adjust="tukey")
```

### By BNT

```{r stats edu, echo=FALSE}
m.acc.edu = glmer(Accuracy ~ Dimension*Group + Education + (1|Category) + (1|Participant), 
                      family = binomial(), 
                      data = dat, control = glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))

m.acc.edu.BNT = glmer(Accuracy ~ Education + cBNT*Dimension + (1|Category) + (1|Participant), 
                      family = binomial(), data = dat, 
                     control = glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))
summary(m.acc.edu.BNT)
```

### Model comparison
```{r model comparison acc, echo=FALSE}
modelcomp.acc = data.frame(
  Model=c('Group x Dim', 'Group x Dim + Edu', 'BNT x Dim + Edu'),
  AIC=c(AIC(m.acc), AIC(m.acc.edu), AIC(m.acc.edu.BNT)))
write.csv(modelcomp.acc, 'Tables/E2_ModelComparison_Accuracy.csv')
```

## Plots

```{r plot acc, echo=FALSE}
dat2plot.acc = dat %>%
  mutate(Group=factor(Group, levels=c('Neurotypical', 'Aphasia', 'Parkinsons'))) %>%
  group_by(Group,Dimension,Participant,BNT) %>%
  summarize(Accuracy=mean(Accuracy))

e2_acc = ggplot(data=dat2plot.acc, mapping=aes(x=Group, y=Accuracy, fill=Dimension))+
  stat_summary(geom = 'col', fun.y = 'mean', width=0.5, 
               position='dodge', show.legend=FALSE)+
  geom_point(position=position_jitterdodge(dodge.width=0.5, jitter.height=0, jitter.width=0.1),
             shape=21, size=1.5, alpha=0.5, show.legend = FALSE)+
  stat_summary(geom = 'errorbar', fun.data = 'mean_se', width=0.15, size=0.75,
               position=position_dodge(width=0.5))+
  coord_cartesian(ylim=c(0.5,1))+
  labs(y='Accuracy', x=NULL)+
  scale_x_discrete(labels=c("Neurotypical", "Aphasia", "PD"))+
  scale_fill_manual(values=c('#0A730A', '#98CD92'))+
  theme_classic()+
  theme(axis.title.y=element_text(size=14),
        axis.text.x=element_text(size=14),
        axis.text.y=element_text(size=10))

e2_acc 
```

```{r plot BNT, echo=FALSE}
e2_acc_bnt = ggplot(data=dat2plot.acc)+
  geom_point(mapping=aes(x=BNT, y=Accuracy, fill=Dimension),
            shape=21, size=1.5, color='darkgray', show.legend=FALSE)+
  geom_smooth(method='lm', mapping=aes(x=BNT, y=Accuracy, color=Dimension),
              alpha=0.2, size=1.5, show.legend=FALSE)+
  scale_color_manual(values=c('#0A730A', '#98CD92'))+
  scale_fill_manual(values=c('#0A730A', '#98CD92'))+
  coord_cartesian(ylim=c(0.72,1))+
  labs(y='Accuracy')+
  theme_classic()+
  theme(axis.title.x=element_text(size=14),
        axis.title.y=element_text(size=14),
        axis.text.x=element_text(size=11),
        axis.text.y=element_text(size=11))
e2_acc_bnt 
```


# RT

## Stats

### By Group
```{r stats RT, echo=FALSE}
m.RT = lmer(Response.Time ~ Dimension*Group + (1|Category) + (1|Participant), 
            data = dat, REML = FALSE)
summary(m.RT)
```

####Follow-up comparisons
```{r stats pairwise FA, echo=FALSE}
d = emmeans(m.RT, ~ Dimension) %>% 
    contrast("pairwise") 

emmeans(m.RT, ~ Group * Dimension) %>% 
    contrast("pairwise", by = "Group") %>% 
    rbind(d) %>%
    summary(by=NULL, adjust="tukey")
```

### By BNT

```{r stats FA BNT, echo=FALSE}
m.RT.edu = lmer(Response.Time ~ Dimension*Group + Education + (1|Category) + (1|Participant), 
            data = dat, REML = FALSE)
m.RT.edu.BNT = lmer(Response.Time ~ Education + cBNT*Dimension + (1|Category) + (1|Participant), 
            data = dat, REML = FALSE)

summary(m.RT.edu.BNT)
```

### Model selection

```{r model comparison acc, echo=FALSE}
modelcomp.RT = data.frame(
  Model=c('Group x Dim', 'Group x Dim + Edu', 'BNT x Dim + Edu'),
  AIC=c(AIC(m.RT), AIC(m.RT.edu), AIC(m.RT.edu.BNT)))
write.csv(modelcomp.RT, 'Tables/E2_ModelComparison_ResponseTime.csv')
```

## Plots

```{r plot FalseAlarm, echo=FALSE}
dat2plot.RT = dat %>%
  mutate(Group=factor(Group, levels=c('Neurotypical', 'Aphasia', 'Parkinsons'))) %>%
  group_by(Group,Dimension,Participant,BNT) %>%
  summarize(Response.Time=mean(Response.Time))

e2_rt = ggplot(data=dat2plot.RT, mapping=aes(x=Group, y=Response.Time, fill=Dimension))+
  stat_summary(geom = 'col', fun.y = 'mean', width=0.5, 
               position='dodge')+
  geom_point(position=position_jitterdodge(dodge.width=0.5, jitter.height=0, jitter.width=0.1),
             shape=21, size=1.5, alpha=0.5, show.legend = FALSE)+
  stat_summary(geom = 'errorbar', fun.data = 'mean_se', width=0.15, size=0.75,
               position=position_dodge(width=0.5))+
  #coord_cartesian(ylim=c(0,0.1))+
  labs(y='Response Time (s)', x=NULL)+
  scale_x_discrete(labels=c("Neurotypical", "Aphasia", "PD"))+
  scale_fill_manual(values=c('#0A730A', '#98CD92'))+
  theme_classic()+
  theme(axis.title.y=element_text(size=14),
                axis.text.x=element_text(size=14),
        legend.title = element_text(size=14),
        legend.text = element_text(size=12))
e2_rt
```

```{r plot BNT, echo=FALSE}
e2_rt_bnt = ggplot(data=dat2plot.RT)+
  geom_point(mapping=aes(x=BNT, y=Response.Time, fill=Dimension),
            shape=21, size=1.5, color='darkgray', show.legend=FALSE)+
  geom_smooth(method='lm', mapping=aes(x=BNT, y=Response.Time, color=Dimension),
              alpha=0.2, size=1.5)+
  scale_color_manual(values=c('#0A730A', '#98CD92'))+
  scale_fill_manual(values=c('#0A730A', '#98CD92'))+
  labs(y='Response Time (s)')+
  #coord_cartesian(ylim=c(0,65))+
  theme_classic()+
  theme(axis.title.x=element_text(size=14),
        axis.title.y=element_text(size=14),
        axis.text.x=element_text(size=11),
        axis.text.y=element_text(size=11),
        legend.title = element_text(size=14),
        legend.text = element_text(size=12))

e2_rt_bnt
```


# COMBINE

```{r combine plots, echo=FALSE}
(e2_acc |plot_spacer() |e2_rt |
   plot_layout(widths=c(1,0.1,1))) / 
  plot_spacer() / 
  (e2_acc_bnt |plot_spacer() |e2_rt_bnt |
     plot_layout(widths=c(1,0.1,1))) /
  plot_layout(heights=c(1,0.1,1))
ggsave('Plots/E2_results_acc_RT.png', width=25, height=20, units='cm')
```

